"""Top-level public API for the refactored nuGUNDAM package."""
from .angular_public import (
    AngularAutoConfig,
    AngularAutoCountsConfig,
    AngularCrossConfig,
    AngularCrossCountsConfig,
    AngularBinning,
    AngularGridSpec,
    WeightSpec,
    BootstrapSpec,
    JackknifeSpec,
    ProgressSpec,
    SplitRandomSpec,
    CatalogColumns,
    AngularAutoCounts,
    AngularAutoCountsResult,
    AngularCrossCounts,
    AngularCrossCountsResult,
    AngularCorrelationResult,
    ang_auto_counts,
    ang_cross_counts,
    acf,
    accf,
    save_result,
    write_result,
    read_result,
    plotcf,
    plotcf2d,
    plot_result,
    plot_result2d,
    plot_cov_matrix,
    plot_corr_matrix,
    plot_jk_regions,
    plot_compare_ratio,
    result_to_dict,
)

from .projected_public import (
    ProjectedCatalogColumns,
    ProjectedBinning,
    ProjectedGridSpec,
    SplitRandomSpec as ProjectedSplitRandomSpec,
    BootstrapSpec as ProjectedBootstrapSpec,
    JackknifeSpec as ProjectedJackknifeSpec,
    DistanceSpec,
    ProjectedAutoConfig,
    ProjectedCrossConfig,
    ProjectedAutoCountsConfig,
    ProjectedCrossCountsConfig,
    PreparedProjectedSample,
    ProjectedAutoCounts,
    ProjectedAutoCountsResult,
    ProjectedCrossCounts,
    ProjectedCrossCountsResult,
    ProjectedCorrelationResult,
    proj_auto_counts,
    proj_cross_counts,
    pcf,
    pccf,
)


from .marked import (
    AutoMarkSpec,
    CrossMarkSpec,
    MarkedAngularCorrelationResult,
    MarkedProjectedCorrelationResult,
    macf,
    maccf,
    mpcf,
    mpccf,
)
